import type { CSSProperties } from "react";
import type { LucideProps } from "lucide-react";
import {
  Accessibility,
  AlignHorizontalDistributeCenter,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignVerticalDistributeCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowLeftRight,
  AtSign,
  BadgeAlert,
  BadgeCheck,
  Ban,
  BarChart3,
  Bold,
  BookOpenText,
  Bookmark,
  Brush,
  CalendarDays,
  CameraOff,
  Cast,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Church,
  Circle,
  CircleDot,
  Clapperboard,
  ClipboardList,
  Clock,
  Code,
  Columns2,
  Combine,
  Compass,
  Contact,
  Contrast,
  Copy,
  Crop,
  Crosshair,
  Database,
  Delete,
  Download,
  DownloadCloud,
  Droplets,
  Eraser,
  Eye,
  EyeOff,
  ExternalLink,
  File,
  FilePenLine,
  FileText,
  Film,
  Filter,
  FolderOpen,
  Gauge,
  Globe,
  Grid3x3,
  Grip,
  GripVertical,
  Hand,
  Heading,
  HelpCircle,
  Heart,
  History,
  Hourglass,
  Image,
  ImageOff,
  Images,
  Infinity,
  Info,
  Keyboard,
  Languages,
  Layers,
  Layers2,
  Layers3,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  Library,
  LibraryBig,
  Link,
  Link2Off,
  ListChecks,
  ListMusic,
  ListPlus,
  ListX,
  Lock,
  MapPin,
  Maximize,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  MicOff,
  MicVocal,
  Minimize,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  MoveDown,
  Music,
  Music4,
  PackageOpen,
  Palette,
  Pause,
  Pencil,
  Play,
  PlayCircle,
  Podcast,
  Plus,
  Power,
  Presentation,
  Quote,
  Radio,
  Receipt,
  Redo,
  RefreshCw,
  Rocket,
  RotateCw,
  Ruler,
  Save,
  Search,
  SearchX,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  SkipBack,
  SkipForward,
  Sliders,
  Sparkles,
  Square,
  SquarePen,
  Star,
  StopCircle,
  SunMedium,
  SwitchCamera,
  Theater,
  Timer,
  ToyBrick,
  Trash,
  Trash2,
  Tv,
  Type,
  Undo,
  Upload,
  UploadCloud,
  User,
  UserMinus,
  UserPlus,
  Video,
  VideoOff,
  Volume2,
  VolumeX,
  Wand2,
  Wifi,
  X,
  Zap,
} from "lucide-react";

interface Props {
  name: string;
  size?: number;
  className?: string;
  style?: CSSProperties;
}

type IconDef = {
  component: React.FC<LucideProps>;
  fill?: boolean;
  strokeWidth?: number;
};

const ICONS: Record<string, IconDef> = {
  accessibility_new: { component: Accessibility },
  add: { component: Plus },
  add_box: { component: Square },
  add_circle: { component: CheckCircle },
  add_circle_outline: { component: CheckCircle },
  add_photo_alternate: { component: Image },
  align_horizontal_center: { component: AlignHorizontalDistributeCenter },
  align_horizontal_left: { component: AlignHorizontalJustifyStart },
  align_horizontal_right: { component: AlignHorizontalSpaceAround },
  align_vertical_bottom: { component: AlignVerticalJustifyEnd },
  align_vertical_center: { component: AlignVerticalDistributeCenter },
  align_vertical_top: { component: AlignVerticalJustifyStart },
  all_inclusive: { component: Infinity },
  alternate_email: { component: AtSign },
  animation: { component: Sparkles },
  apps: { component: Grid3x3 },
  archive: { component: Archive },
  arrow_back: { component: ArrowLeft },
  arrow_downward: { component: ArrowDown },
  arrow_drop_down: { component: ChevronDown },
  arrow_drop_up: { component: ChevronUp },
  arrow_forward: { component: ArrowRight },
  arrow_forward_ios: { component: ChevronRight },
  arrow_upward: { component: ArrowUp },
  aspect_ratio: { component: Crop },
  assignment: { component: FileText },
  auto_awesome: { component: Sparkles },
  auto_awesome_mosaic: { component: ToyBrick },
  auto_fix_high: { component: Wand2 },
  auto_stories: { component: Languages },
  block: { component: Ban },
  bolt: { component: Zap },
  bookmark: { component: Bookmark },
  branding_watermark: { component: Droplets },
  broadcast_on_personal: { component: Radio },
  brush: { component: Brush },
  build: { component: Settings2 },
  call_to_action: { component: Megaphone },
  cameraswitch: { component: SwitchCamera },
  campaign: { component: Megaphone },
  cancel: { component: X },
  cancel_presentation: { component: Presentation },
  cast: { component: Cast },
  cast_connected: { component: Cast },
  cell_tower: { component: Radio },
  chat_bubble_outline: { component: MessageSquare },
  check: { component: Check },
  check_circle: { component: CheckCircle2 },
  checklist: { component: ListChecks },
  chevron_left: { component: ChevronLeft },
  chevron_right: { component: ChevronRight },
  church: { component: Church },
  clear: { component: Eraser },
  close: { component: X },
  close_fullscreen: { component: Minimize },
  cloud_upload: { component: UploadCloud },
  code: { component: Code },
  collections_bookmark: { component: Library },
  content_copy: { component: Copy },
  crop_free: { component: Crosshair },
  dashboard: { component: LayoutDashboard },
  delete: { component: Trash },
  delete_forever: { component: Delete },
  delete_outline: { component: Trash },
  delete_sweep: { component: Trash2 },
  desktop_access_disabled: { component: Monitor },
  desktop_windows: { component: Monitor },
  dock: { component: LayoutPanelLeft },
  download: { component: Download },
  download_done: { component: DownloadCloud },
  drag_indicator: { component: GripVertical },
  edit: { component: Pencil },
  edit_note: { component: SquarePen },
  emergency: { component: ShieldAlert },
  equalizer: { component: BarChart3 },
  error: { component: BadgeAlert },
  error_outline: { component: AlertCircle },
  event: { component: CalendarDays },
  event_note: { component: ClipboardList },
  expand_less: { component: ChevronUp },
  expand_more: { component: ChevronDown },
  explore: { component: Compass },
  fact_check: { component: ListChecks },
  fiber_manual_record: { component: Circle, fill: true, strokeWidth: 0 },
  filter_list: { component: Filter },
  format_align_center: { component: AlignCenter },
  format_align_left: { component: AlignLeft },
  format_align_right: { component: AlignRight },
  format_bold: { component: Bold },
  format_quote: { component: Quote },
  fullscreen: { component: Maximize },
  graphic_eq: { component: BarChart3 },
  grid_4x4: { component: Grid3x3 },
  grid_on: { component: Grid3x3 },
  grid_view: { component: LayoutGrid },
  headphones: { component: Radio },
  help_outline: { component: HelpCircle },
  history: { component: History },
  horizontal_distribute: { component: AlignHorizontalDistributeCenter },
  hourglass_empty: { component: Hourglass },
  hourglass_top: { component: Timer },
  image: { component: Image },
  image_not_supported: { component: ImageOff },
  info: { component: Info },
  insert_drive_file: { component: File },
  install_desktop: { component: Monitor },
  keyboard: { component: Keyboard },
  keyboard_arrow_down: { component: ChevronDown },
  language: { component: Globe },
  layers: { component: Layers },
  layers_clear: { component: Layers2 },
  library_books: { component: LibraryBig },
  library_music: { component: ListMusic },
  link: { component: Link },
  link_off: { component: Link2Off },
  live_tv: { component: Tv },
  lock: { component: Lock },
  lyrics: { component: Music },
  book_open: { component: BookOpenText },
  menu: { component: Menu },
  menu_book: { component: BookOpenText },
  merge_type: { component: Combine },
  mic: { component: Mic },
  mic_off: { component: MicOff },
  monitor: { component: Monitor },
  monitor_heart: { component: Heart },
  more_horiz: { component: MoreHorizontal },
  more_vert: { component: MoreVertical },
  moon: { component: SunMedium },
  movie: { component: Film },
  move_down: { component: MoveDown },
  music_note: { component: Music },
  music_off: { component: Music4 },
  name: { component: Contact },
  no_photography: { component: CameraOff },
  opacity: { component: Contrast },
  open_in_new: { component: ExternalLink },
  open_with: { component: Grip },
  palette: { component: Palette },
  pause: { component: Pause },
  pause_presentation: { component: Presentation },
  perm_media: { component: FolderOpen },
  person: { component: User },
  person_add: { component: UserPlus },
  person_off: { component: UserMinus },
  photo_library: { component: Images },
  place: { component: MapPin },
  play: { component: Play },
  play_arrow: { component: Play },
  play_circle: { component: Clapperboard },
  play_circle_outline: { component: PlayCircle },
  playlist_add: { component: ListPlus },
  playlist_play: { component: ListMusic },
  playlist_remove: { component: ListX },
  podcasts: { component: Podcast },
  power_off: { component: Power },
  power_settings_new: { component: Power },
  preview: { component: Eye },
  push_pin: { component: CheckSquare },
  queue: { component: ListPlus },
  radio_button_checked: { component: CircleDot },
  radio_button_unchecked: { component: Circle },
  receipt_long: { component: Receipt },
  record_voice_over: { component: MicVocal },
  redo: { component: Redo },
  refresh: { component: RefreshCw },
  remove: { component: Minus },
  replay: { component: RefreshCw },
  restart_alt: { component: RotateCw },
  rocket: { component: Rocket },
  rocket_launch: { component: Rocket },
  save: { component: Save },
  schedule: { component: Clock },
  search: { component: Search },
  search_off: { component: SearchX },
  select_all: { component: CheckSquare },
  self_improvement: { component: Church },
  send: { component: Send },
  settings: { component: Settings },
  settings_input_antenna: { component: Radio },
  shadow: { component: Contrast },
  shield: { component: Shield },
  short_text: { component: Type },
  skip_next: { component: SkipForward },
  skip_previous: { component: SkipBack },
  slideshow: { component: Presentation },
  speed: { component: Gauge },
  splitscreen: { component: Columns2 },
  sports_esports: { component: Radio },
  star: { component: Star, fill: true, strokeWidth: 1.8 },
  star_border: { component: Star },
  stop: { component: Square },
  stop_circle: { component: StopCircle },
  storage: { component: Database },
  straighten: { component: Ruler },
  subtitles: { component: FilePenLine },
  sun: { component: SunMedium },
  swap_calls: { component: ArrowUpDown },
  swap_horiz: { component: ArrowLeftRight },
  switch_video: { component: SwitchCamera },
  sync: { component: RefreshCw },
  text_fields: { component: Type },
  theaters: { component: Theater },
  timer: { component: Timer },
  title: { component: Heading },
  touch_app: { component: Hand },
  translate: { component: Languages },
  travel_explore: { component: Globe },
  tune: { component: Sliders },
  tv: { component: Tv },
  tv_off: { component: Monitor },
  unarchive: { component: PackageOpen },
  undo: { component: Undo },
  upload: { component: Upload },
  upload_file: { component: UploadCloud },
  verified: { component: BadgeCheck },
  vertical_align_center: { component: AlignVerticalDistributeCenter },
  vertical_distribute: { component: AlignVerticalDistributeCenter },
  vertical_split: { component: LayoutPanelLeft },
  video_library: { component: Video },
  videocam: { component: Video },
  videocam_off: { component: VideoOff },
  view_carousel: { component: LayoutGrid },
  view_column: { component: Columns2 },
  view_quilt: { component: LayoutList },
  visibility: { component: Eye },
  visibility_off: { component: EyeOff },
  volunteer_activism: { component: Heart },
  volume_off: { component: VolumeX },
  volume_up: { component: Volume2 },
  wallpaper: { component: Image },
  warning: { component: AlertTriangle },
  wifi: { component: Wifi },
  wifi_tethering: { component: Wifi },
  widgets: { component: Layers3 },
};

export default function DockIcon({ name, size = 16, className, style }: Props) {
  const def = ICONS[name] ?? ICONS.widgets;
  const Component = def.component;
  const iconProps: LucideProps = {
    size,
    className,
    style,
    strokeWidth: def.strokeWidth ?? 2,
  };

  if (def.fill) {
    iconProps.fill = "currentColor";
  }

  return <Component {...iconProps} />;
}
