import type { MediaItem } from "../library/libraryTypes";

/**
 * Files generated by Dock features for OBS implementation details. They are
 * not user media and should never be offered in a user-facing media picker.
 */
const INTERNAL_DOCK_UPLOAD_PREFIXES = ["mv-frame-", "mv-pattern-"] as const;

function getFileName(value: string): string {
  const parts = value.split(/[\\/]/);
  return (parts[parts.length - 1] || value).trim().toLowerCase();
}

export function isInternalDockUploadFile(value: string): boolean {
  const fileName = getFileName(value);
  return INTERNAL_DOCK_UPLOAD_PREFIXES.some((prefix) => fileName.startsWith(prefix));
}

export function isInternalDockMediaItem(item: Pick<MediaItem, "name" | "filePath" | "diskFileName">): boolean {
  return [item.name, item.filePath, item.diskFileName]
    .filter((value): value is string => Boolean(value))
    .some(isInternalDockUploadFile);
}
