#!/usr/bin/env python3
"""
Add title attributes to all <button> elements that lack one.
Reads each .tsx file, finds buttons without title=, and adds one based on context.

Strategy:
1. If button has text-only children → use text as title
2. If button has Icon with name prop → map icon name to description
3. If button is in common patterns (close, delete, etc.) → use pattern-based title
4. Fallback → generic "Action" title
"""

import re
import os
import sys

# Icon name → human-readable description
ICON_MAP = {
    "close": "Close",
    "delete": "Delete",
    "edit": "Edit",
    "add": "Add",
    "remove": "Remove",
    "save": "Save",
    "search": "Search",
    "refresh": "Refresh",
    "settings": "Settings",
    "menu": "Menu",
    "arrow_back": "Go back",
    "arrow_forward": "Go forward",
    "chevron_left": "Previous",
    "chevron_right": "Next",
    "expand_more": "Show more",
    "expand_less": "Show less",
    "keyboard_arrow_up": "Move up",
    "keyboard_arrow_down": "Move down",
    "keyboard_arrow_left": "Previous",
    "keyboard_arrow_right": "Next",
    "star": "Favorite",
    "star_border": "Add to favorites",
    "favorite": "Favorite",
    "favorite_border": "Add to favorites",
    "visibility": "Show",
    "visibility_off": "Hide",
    "content_copy": "Copy",
    "content_paste": "Paste",
    "content_cut": "Cut",
    "undo": "Undo",
    "redo": "Redo",
    "download": "Download",
    "upload": "Upload",
    "share": "Share",
    "link": "Copy link",
    "open_in_new": "Open in new tab",
    "play": "Play",
    "pause": "Pause",
    "stop": "Stop",
    "skip_next": "Next",
    "skip_previous": "Previous",
    "replay": "Replay",
    "volume_up": "Increase volume",
    "volume_down": "Decrease volume",
    "volume_off": "Mute",
    "fullscreen": "Fullscreen",
    "fullscreen_exit": "Exit fullscreen",
    "minimize": "Minimize",
    "maximize": "Maximize",
    "drag_indicator": "Drag to reorder",
    "swap_horiz": "Swap",
    "swap_vert": "Swap",
    "sync": "Sync",
    "cloud_upload": "Upload to cloud",
    "cloud_download": "Download from cloud",
    "wifi": "Connect",
    "wifi_off": "Disconnect",
    "power_settings_new": "Power",
    "logout": "Log out",
    "login": "Log in",
    "person": "Profile",
    "group": "Team",
    "lock": "Lock",
    "lock_open": "Unlock",
    "vpn_key": "Activate",
    "check": "Confirm",
    "check_circle": "Confirm",
    "cancel": "Cancel",
    "warning": "Warning",
    "info": "Information",
    "help": "Help",
    "more_vert": "More options",
    "more_horiz": "More options",
    "sort": "Sort",
    "filter_list": "Filter",
    "tune": "Adjust settings",
    "palette": "Color picker",
    "brush": "Paint",
    "format_color_fill": "Fill color",
    "text_fields": "Text settings",
    "format_bold": "Bold",
    "format_italic": "Italic",
    "format_underline": "Underline",
    "format_align_left": "Align left",
    "format_align_center": "Align center",
    "format_align_right": "Align right",
    "zoom_in": "Zoom in",
    "zoom_out": "Zoom out",
    "fit_screen": "Fit to screen",
    "crop": "Crop",
    "rotate_left": "Rotate left",
    "rotate_right": "Rotate right",
    "flip": "Flip",
    "auto_fix_high": "Auto enhance",
    "auto_fix_normal": "Auto fix",
    "brightness_high": "Increase brightness",
    "brightness_low": "Decrease brightness",
    "contrast": "Adjust contrast",
    "blur_on": "Blur",
    "blur_off": "Remove blur",
    "animation": "Animation",
    "slideshow": "Slideshow",
    "view_module": "Grid view",
    "view_list": "List view",
    "dashboard": "Dashboard",
    "home": "Home",
    "inbox": "Inbox",
    "notifications": "Notifications",
    "mail": "Messages",
    "chat": "Chat",
    "phone": "Call",
    "videocam": "Video",
    "camera": "Camera",
    "mic": "Microphone",
    "mic_off": "Mute microphone",
    "music_note": "Music",
    "audiotrack": "Audio track",
    "queue_music": "Music queue",
    "library_music": "Music library",
    "movie": "Video",
    "image": "Image",
    "photo_library": "Photo library",
    "folder": "Folder",
    "folder_open": "Open folder",
    "create_new_folder": "New folder",
    "file_copy": "Copy file",
    "description": "Description",
    "note": "Note",
    "bookmark": "Bookmark",
    "bookmark_border": "Remove bookmark",
    "label": "Label",
    "flag": "Flag",
    "archive": "Archive",
    "restore": "Restore",
    "history": "History",
    "schedule": "Schedule",
    "event": "Event",
    "calendar_today": "Calendar",
    "alarm": "Alarm",
    "timer": "Timer",
    "stopwatch": "Stopwatch",
    "code": "Code",
    "terminal": "Terminal",
    "bug_report": "Report bug",
    "build": "Build",
    "engineering": "Settings",
    "science": "Tools",
    "medical_services": "Health",
    "local_hospital": "Hospital",
    "school": "Education",
    "menu_book": "Book",
    "library_books": "Library",
    "collections": "Collections",
    "auto_stories": "Stories",
    "translate": "Translate",
    "globe": "Web",
    "public": "Public",
    "link_off": "Remove link",
    "content_cut": "Cut",
    "select_all": "Select all",
    "deselect": "Deselect all",
    "radio_button_checked": "Selected",
    "radio_button_unchecked": "Not selected",
    "check_box": "Checked",
    "check_box_outline_blank": "Unchecked",
    "toggle_on": "Turn on",
    "toggle_off": "Turn off",
    "swap_horiz": "Swap",
    "compare": "Compare",
    "scatter_plot": "Chart",
    "insert_chart": "Insert chart",
    "timeline": "Timeline",
    "analytics": "Analytics",
    "insights": "Insights",
    "trending_up": "Trending up",
    "trending_down": "Trending down",
    "assessment": "Assessment",
    "monitor_heart": "Monitor",
    "speed": "Speed",
    "done_all": "All done",
    "mark_email_read": "Mark as read",
    "mark_email_unread": "Mark as unread",
    "send": "Send",
    "forward": "Forward",
    "reply": "Reply",
    "reply_all": "Reply all",
    "archive": "Archive",
    "delete_sweep": "Delete all",
    "mark_chat_read": "Mark as read",
    "push_pin": "Pin",
    "push_pin_outlined": "Unpin",
    "lock_clock": "Locked",
    "https": "Open URL",
    "content_paste_go": "Paste",
    "content_paste_off": "Cannot paste",
    "keyboard": "Keyboard",
    "smart_toy": "AI",
    "robot": "Robot",
    "psychology": "Brain",
    "lightbulb": "Idea",
    "tips_and_updates": "Tips",
    "notifications_active": "Notifications on",
    "notifications_off": "Notifications off",
    "volume_up": "Volume up",
    "equalizer": "Equalizer",
    "surround_sound": "Surround sound",
    "graphic_eq": "EQ",
    "settings_input_hdmi": "HDMI input",
    "settings_input_antenna": "Antenna input",
    "settings_remote": "Remote settings",
    "tune": "Tune",
    "signal_cellular_alt": "Signal strength",
    "battery_full": "Battery",
    "battery_charging_full": "Charging",
    "power": "Power",
    "restart_alt": "Restart",
    "upgrade": "Upgrade",
    "system_update": "System update",
    "autorenew": "Auto refresh",
    "cached": "Cached",
    "refresh": "Refresh",
    "loop": "Repeat",
    "shuffle": "Shuffle",
    "repeat": "Repeat",
    "repeat_one": "Repeat one",
    "fast_forward": "Fast forward",
    "fast_rewind": "Rewind",
    "graphic_eq": "Equalizer",
    "playlist_play": "Playlist",
    "queue": "Queue",
    "queue_music": "Music queue",
    "music_video": "Video",
    "live_tv": "Live TV",
    "cast": "Cast",
    "screen_share": "Share screen",
    "airplay": "AirPlay",
    "bluetooth": "Bluetooth",
    "nfc": "NFC",
    "signal_wifi_4_bar": "WiFi",
    "signal_cellular_4_bar": "Cellular",
    "rss_feed": "RSS",
    "webhook": "Webhook",
    "api": "API",
    "cloud": "Cloud",
    "storage": "Storage",
    "database": "Database",
    "memory": "Memory",
    "sd_card": "SD card",
    "usb": "USB",
    "print": "Print",
    "save": "Save",
    "save_alt": "Save as",
    "file_download": "Download file",
    "file_upload": "Upload file",
    "attach_file": "Attach file",
    "attachment": "Attachment",
    "image": "Image",
    "videocam": "Video",
    "audiotrack": "Audio",
    "insert_drive_file": "File",
    "draft": "Draft",
    "article": "Article",
    "note_add": "Add note",
    "edit_note": "Edit note",
    "document_scanner": "Scan",
    "fax": "Fax",
    "local_print_shop": "Print",
    "local_post_office": "Post",
    "markunread_mailbox": "Inbox",
    "move_to_inbox": "Move to inbox",
    "add_task": "Add task",
    "task_alt": "Complete task",
    "playlist_add": "Add to playlist",
    "queue_music": "Queue music",
    "library_music": "Music library",
    "mic_external_on": "External mic",
    "surround_sound": "Surround sound",
    "hearing": "Hearing",
    "hearing_disabled": "Hearing disabled",
    "closed_caption": "Captions",
    "closed_caption_disabled": "Captions off",
    "subtitles": "Subtitles",
    "subtitles_off": "Subtitles off",
    "accessibility_new": "Accessibility",
    "accessible": "Accessible",
    "accessible_forward": "Accessible forward",
    "emoji_events": "Trophy",
    "military_tech": "Medal",
    "workspace_premium": "Premium",
    "card_giftcard": "Gift card",
    "redeem": "Redeem",
    "loyalty": "Loyalty",
    "paid": "Paid",
    "account_balance_wallet": "Wallet",
    "savings": "Savings",
    "receipt_long": "Receipt",
    "local_atm": "ATM",
    "account_balance": "Bank",
    "credit_card": "Credit card",
    "add_card": "Add card",
    "remove_shopping_cart": "Remove from cart",
    "add_shopping_cart": "Add to cart",
    "shopping_cart": "Cart",
    "shopping_bag": "Bag",
    "storefront": "Store",
    "local_mall": "Mall",
    "local_offer": "Offer",
    "sell": "Sell",
    "payments": "Payments",
    "request_quote": "Get quote",
    "monetization_on": "Monetization",
    "show_chart": "Chart",
    "insert_chart_outlined": "Insert chart",
    "pie_chart": "Pie chart",
    "bar_chart": "Bar chart",
    "stacked_line_chart": "Line chart",
    "area_chart": "Area chart",
    "bubble_chart": "Bubble chart",
    "candlestick_chart": "Candlestick",
    "trek": "Trek",
    "explore": "Explore",
    "explore_off": "Explore off",
    "near_me": "Near me",
    "near_me_disabled": "Near me disabled",
    "directions": "Directions",
    "directions_car": "Car directions",
    "directions_walk": "Walk directions",
    "directions_bike": "Bike directions",
    "directions_bus": "Bus directions",
    "flight": "Flight",
    "train": "Train",
    "subway": "Subway",
    "tram": "Tram",
    "hotel": "Hotel",
    "beach_access": "Beach",
    "pool": "Pool",
    "spa": "Spa",
    "fitness_center": "Gym",
    "sports_esports": "Gaming",
    "sports_soccer": "Soccer",
    "sports_basketball": "Basketball",
    "sports_football": "Football",
    "sports_baseball": "Baseball",
    "sports_tennis": "Tennis",
    "sports_golf": "Golf",
    "sports_hockey": "Hockey",
    "sports_cricket": "Cricket",
    "sports_rugby": "Rugby",
    "sports_volleyball": "Volleyball",
    "emoji_symbols": "Symbols",
    "emoji_people": "People",
    "emoji_nature": "Nature",
    "emoji_food_beverage": "Food",
    "emoji_transportation": "Transport",
    "emoji_objects": "Objects",
    "emoji_flags": "Flags",
    "thumb_up": "Like",
    "thumb_down": "Dislike",
    "mood": "Mood",
    "mood_bad": "Bad mood",
    "sentiment_satisfied": "Satisfied",
    "sentiment_dissatisfied": "Dissatisfied",
    "sentiment_very_dissatisfied": "Very dissatisfied",
    "sentiment_neutral": "Neutral",
    "local_fire_department": "Fire",
    "local_police": "Police",
    "security": "Security",
    "shield": "Shield",
    "gavel": "Gavel",
    "balance": "Balance",
    "rule": "Rule",
    "policy": "Policy",
    "verified": "Verified",
    "new_releases": "New release",
    "workspace_premium": "Premium",
    "rocket_launch": "Launch",
    "flight_takeoff": "Takeoff",
    "flight_land": "Land",
    "public": "Public",
    "wb_sunny": "Sunny",
    "nightlight_round": "Night",
    "dark_mode": "Dark mode",
    "light_mode": "Light mode",
    "brightness_6": "Brightness",
    "contrast": "Contrast",
    "water_drop": "Water",
    "local_fire_department": "Fire",
    "grass": "Grass",
    "park": "Park",
    "forest": "Forest",
    "landscape": "Landscape",
    "terrain": "Terrain",
    "map": "Map",
    "layers": "Layers",
    "grid_on": "Grid",
    "grid_off": "No grid",
    "drag_handle": "Drag",
    "drag_indicator": "Drag to reorder",
    "open_with": "Move",
    "aspect_ratio": "Aspect ratio",
    "crop_free": "Crop free",
    "crop_square": "Crop square",
    "crop_landscape": "Crop landscape",
    "crop_portrait": "Crop portrait",
    "straighten": "Straighten",
    "tune": "Adjust",
    "flare": "Flare",
    "grain": "Grain",
    "hdr_strong": "HDR",
    "hdr_weak": "HDR weak",
    "hdr_on": "HDR on",
    "hdr_off": "HDR off",
    "deblur": "Deblur",
    "dehaze": "Dehaze",
    "details": "Details",
    "info": "Info",
    "help_outline": "Help",
    "lightbulb": "Tip",
    "tips_and_updates": "Tips",
    "notifications": "Notifications",
    "notifications_active": "Notifications on",
    "notifications_off": "Notifications off",
    "notifications_none": "No notifications",
    "circle_notifications": "Notifications",
    "pending": "Pending",
    "hourglass_empty": "Loading",
    "hourglass_top": "Loading",
    "more_horiz": "More",
    "more_vert": "More options",
    "unfold_more": "Expand all",
    "unfold_less": "Collapse all",
    "chevron_right": "Open",
    "chevron_left": "Back",
    "expand_more": "Expand",
    "expand_less": "Collapse",
    "arrow_drop_up": "Open",
    "arrow_drop_down": "Close",
    "arrow_right": "Go to",
    "arrow_left": "Go back",
    "arrow_upward": "Move up",
    "arrow_downward": "Move down",
    "north": "Move up",
    "south": "Move down",
    "east": "Move right",
    "west": "Move left",
    "first_page": "First page",
    "last_page": "Last page",
    "navigate_next": "Next",
    "navigate_before": "Previous",
    "keyboard_double_arrow_left": "First",
    "keyboard_double_arrow_right": "Last",
    "keyboard_double_arrow_up": "Top",
    "keyboard_double_arrow_down": "Bottom",
    "arrow_back": "Back",
    "arrow_forward": "Forward",
    "call_made": "Open link",
    "call_received": "Receive",
    "launch": "Open",
    "open_in_browser": "Open in browser",
    "picture_in_picture": "Picture in picture",
    "picture_in_picture_alt": "Picture in picture",
    "web_asset": "Web asset",
    "apps": "Apps",
    "dashboard_customize": "Customize",
    "web_stories": "Stories",
    "extension": "Extension",
    "integration_instructions": "Instructions",
    "description": "Description",
    "summarize": "Summary",
    "text_snippet": "Snippet",
    "code": "Code",
    "data_object": "Data",
    "storage": "Storage",
    "cloud": "Cloud",
    "cloud_sync": "Cloud sync",
    "cloud_done": "Cloud done",
    "cloud_off": "Cloud off",
    "cloud_queue": "Cloud queue",
    "cloud_download": "Cloud download",
    "cloud_upload": "Cloud upload",
    "cloud_circle": "Cloud",
    "cloud_upload": "Upload",
    "cloud_download": "Download",
    "movie_filter": "Movie filter",
    "audiotrack": "Audio track",
    "music_off": "Music off",
    "music_note": "Music",
    "music_video": "Music video",
    "library_music": "Music library",
    "queue_music": "Queue",
    "playlist_play": "Playlist",
    "playlist_add": "Add to playlist",
    "playlist_remove": "Remove from playlist",
    "replay": "Replay",
    "replay_10": "Replay 10s",
    "replay_30": "Replay 30s",
    "forward_10": "Forward 10s",
    "forward_30": "Forward 30s",
    "speed": "Speed",
    "closed_caption": "Captions",
    "closed_caption_off": "Captions off",
    "subtitles": "Subtitles",
    "skip_next": "Next",
    "skip_previous": "Previous",
    "play_arrow": "Play",
    "pause": "Pause",
    "stop": "Stop",
    "volume_up": "Volume up",
    "volume_down": "Volume down",
    "volume_off": "Mute",
    "volume_mute": "Mute",
    "surround_sound": "Surround sound",
    "graphic_eq": "Equalizer",
    "spatial_audio": "Spatial audio",
    "spatial_audio_off": "Spatial audio off",
    "audiotrack": "Audio track",
    "music_note": "Music",
    "mic": "Microphone",
    "mic_off": "Mute microphone",
    "mic_external_on": "External mic",
    "mic_external_off": "External mic off",
    "keyboard_voice": "Voice input",
    "record_voice_over": "Voice recording",
    "hearing": "Hearing",
    "hearing_disabled": "Hearing disabled",
    "videocam": "Video",
    "videocam_off": "Camera off",
    "stop_circle": "Stop recording",
    "fiber_manual_record": "Record",
    "fiber_smart_record": "Smart record",
    "play_circle": "Play",
    "pause_circle": "Pause",
    "replay_circle": "Replay",
    "cancel": "Cancel",
    "check_circle": "Confirm",
    "error": "Error",
    "warning": "Warning",
    "info": "Info",
    "help": "Help",
    "help_outline": "Help",
    "feedback": "Feedback",
    "bug_report": "Report bug",
    "rate_review": "Review",
    "thumb_up": "Like",
    "thumb_down": "Dislike",
    "emoji_events": "Trophy",
    "military_tech": "Medal",
    "workspace_premium": "Premium",
    "stars": "Rate",
    "star": "Star",
    "star_border": "Star",
    "star_half": "Half star",
    "bookmark": "Bookmark",
    "bookmark_border": "Bookmark",
    "bookmark_add": "Add bookmark",
    "bookmark_remove": "Remove bookmark",
    "bookmark_added": "Bookmarked",
    "label": "Label",
    "label_off": "Remove label",
    "label_important": "Important",
    "new_label": "New label",
    "push_pin": "Pin",
    "push_pin_outlined": "Unpin",
    "flag": "Flag",
    "flag_off": "Unflag",
    "report": "Report",
    "block": "Block",
    "shield": "Shield",
    "gpp_bad": "Warning",
    "gpp_good": "Secure",
    "gpp_maybe": "Unknown",
    "verified": "Verified",
    "verified_user": "Verified user",
    "admin_panel_settings": "Admin settings",
    "manage_accounts": "Manage accounts",
    "person_add": "Add person",
    "person_remove": "Remove person",
    "group_add": "Add group",
    "group_remove": "Remove group",
    "engineering": "Engineering",
    "biotech": "Biotech",
    "science": "Science",
    "psychology": "Psychology",
    "memory": "Memory",
    "hub": "Hub",
    "sensors": "Sensors",
    "mediation": "Mediation",
    "settings_input_antenna": "Antenna",
    "settings_input_component": "Components",
    "settings_input_hdmi": "HDMI",
    "settings_input_svideo": "S-Video",
    "settings_overscan": "Overscan",
    "settings_brightness": "Brightness",
    "settings_contrast": "Contrast",
    "settings_gamma": "Gamma",
    "settings_zebra": "Zebra",
    "settings_remote": "Remote",
    "tune": "Tune",
    "equalizer": "Equalizer",
    "graphic_eq": "Equalizer",
    "surround_sound": "Surround",
    "spatial_audio": "Spatial",
    "settings_ethernet": "Ethernet",
    "settings_cell": "Mobile",
    "settings_wifi": "WiFi",
    "settings_bluetooth": "Bluetooth",
    "settings_nfc": "NFC",
    "nfc": "NFC",
    "qr_code": "QR code",
    "qr_code_scanner": "QR scanner",
    " barcode": "Barcode",
    "nfc": "NFC",
    "key": "Key",
    "password": "Password",
    "pin": "PIN",
    "fingerprint": "Fingerprint",
    "face": "Face",
    "face_retouching_natural": "Face",
    "face_retouching_off": "Face off",
    "visibility": "Show",
    "visibility_off": "Hide",
    "lock": "Lock",
    "lock_open": "Unlock",
    "enhanced_encryption": "Encryption",
    "no_encryption": "No encryption",
    "vpn_key": "VPN",
    "vpn_lock": "VPN lock",
    "add_moderator": "Add moderator",
    "remove_moderator": "Remove moderator",
    "report_gmailerrorred": "Report",
    "shield": "Shield",
    "gavel": "Gavel",
    "account_balance": "Balance",
    "balance": "Balance",
    "balance": "Balance",
    "policy": "Policy",
    "rule": "Rule",
    "gavel": "Gavel",
    "account_tree": "Account tree",
    "assignment": "Assignment",
    "assignment_ind": "Assignment",
    "assignment_late": "Late assignment",
    "assignment_return": "Return",
    "assignment_returned": "Returned",
    "assignment_turned_in": "Completed",
    "pending_actions": "Pending",
    "task_alt": "Completed",
    "add_task": "Add task",
    "playlist_add_check": "Added to queue",
    "edit_calendar": "Edit calendar",
    "calendar_month": "Calendar",
    "today": "Today",
    "date_range": "Date range",
    "update": "Update",
    "system_update_alt": "Update",
    "autorenew": "Auto renew",
    "cached": "Cached",
    "sync": "Sync",
    "sync_disabled": "Sync disabled",
    "sync_problem": "Sync error",
    "loop": "Loop",
    "shuffle": "Shuffle",
    "repeat": "Repeat",
    "repeat_one": "Repeat one",
    "fast_forward": "Fast forward",
    "fast_rewind": "Rewind",
    "skip_next": "Next",
    "skip_previous": "Previous",
    "replay": "Replay",
    "settings_backup_restore": "Restore",
    "restore_from_trash": "Restore",
    "restore_page": "Restore page",
    "history": "History",
    "update_disabled": "Update disabled",
    "sync_problem": "Sync error",
    "cloud_off": "Offline",
    "wifi_off": "WiFi off",
    "signal_cellular_off": "No signal",
    "signal_wifi_0_bar": "No WiFi",
    "flight": "Flight mode",
    "do_not_disturb_on": "Do not disturb",
    "do_not_disturb_off": "DND off",
    "notifications_off": "Notifications off",
    "volume_off": "Volume off",
    "mic_off": "Mic off",
    "videocam_off": "Camera off",
    "screen_lock_landscape": "Lock landscape",
    "screen_lock_portrait": "Lock portrait",
    "screen_lock_rotation": "Lock rotation",
    "screen_rotation": "Rotate",
    "rotate_90_degrees_ccw": "Rotate",
    "rotate_left": "Rotate left",
    "rotate_right": "Rotate right",
    "flip": "Flip",
    "flip_to_back": "Flip to back",
    "flip_to_front": "Flip to front",
    "crop": "Crop",
    "crop_free": "Free crop",
    "crop_landscape": "Landscape crop",
    "crop_portrait": "Portrait crop",
    "crop_square": "Square crop",
    "crop_16_9": "16:9 crop",
    "crop_3_2": "3:2 crop",
    "crop_5_4": "5:4 crop",
    "crop_7_5": "7:5 crop",
    "aspect_ratio": "Aspect ratio",
    "straighten": "Straighten",
    "filter": "Filter",
    "filter_alt": "Filter",
    "filter_list": "Filter list",
    "filter_list_off": "Clear filter",
    "sort": "Sort",
    "sort_by_alpha": "Sort A-Z",
    "unfold_more": "Expand all",
    "unfold_less": "Collapse all",
    "select_all": "Select all",
    "deselect": "Deselect",
    "zoom_in": "Zoom in",
    "zoom_out": "Zoom out",
    "fit_screen": "Fit screen",
    "center_focus_strong": "Center focus",
    "center_focus_weak": "Center focus off",
    "pageview": "Page view",
    "search": "Search",
    "search_off": "Clear search",
    "manage_search": "Manage search",
    "youtube_searched_for": "Recent searches",
    "auto_awesome": "Auto enhance",
    "auto_awesome_mosaic": "Mosaic",
    "auto_awesome_motion": "Motion",
    "auto_fix_high": "Auto enhance",
    "auto_fix_normal": "Normal fix",
    "auto_fix_off": "No fix",
    "color_lens": "Color",
    "palette": "Palette",
    "brush": "Brush",
    "format_paint": "Paint",
    "draw": "Draw",
    "format_color_fill": "Fill",
    "format_color_reset": "Reset color",
    "format_color_text": "Text color",
    "format_bold": "Bold",
    "format_italic": "Italic",
    "format_underlined": "Underline",
    "format_strikethrough": "Strikethrough",
    "format_size": "Size",
    "format_align_left": "Align left",
    "format_align_center": "Align center",
    "format_align_right": "Align right",
    "format_align_justify": "Justify",
    "format_list_bulleted": "Bullet list",
    "format_list_numbered": "Numbered list",
    "format_indent_increase": "Increase indent",
    "format_indent_decrease": "Decrease indent",
    "format_clear": "Clear format",
    "format_quote": "Quote",
    "format_shapes": "Shapes",
    "format_overview": "Overview",
    "format_color_background": "Background color",
    "space_bar": "Space",
    "code": "Code",
    "data_object": "Data object",
    "database": "Database",
    "dns": "DNS",
    "http": "HTTP",
    "https": "HTTPS",
    "vpn_key": "Key",
    "key": "Key",
    "password": "Password",
    "email": "Email",
    "mail": "Mail",
    "alternate_email": "Alternate email",
    "mark_email_read": "Mark read",
    "mark_email_unread": "Mark unread",
    "mark_chat_read": "Mark read",
    "mark_chat_unread": "Mark unread",
    "drafts": "Drafts",
    "send": "Send",
    "forward": "Forward",
    "reply": "Reply",
    "reply_all": "Reply all",
    "archive": "Archive",
    "report": "Report",
    "flag": "Flag",
    "push_pin": "Pin",
    "label": "Label",
    "folder": "Folder",
    "create_new_folder": "New folder",
    "file_copy": "Copy file",
    "file_move": "Move file",
    "drive_file_move": "Move",
    "drive_file_rename_outline": "Rename",
    "drive_file_upload": "Upload",
    "drive_file_download": "Download",
    "folder_special": "Special folder",
    "folder_shared": "Shared folder",
    "folder_open": "Open folder",
    "create": "Create",
    "edit": "Edit",
    "edit_off": "Edit off",
    "edit_note": "Edit note",
    "note": "Note",
    "sticky_note_2": "Sticky note",
    "description": "Description",
    "article": "Article",
    "snippet": "Snippet",
    "text_snippet": "Text snippet",
    "document_scanner": "Scan",
    "scanner": "Scanner",
    "print": "Print",
    "local_print_shop": "Print shop",
    "content_copy": "Copy",
    "content_paste": "Paste",
    "content_cut": "Cut",
    "content_select": "Select",
    "select_all": "Select all",
    "deselect": "Deselect",
    "undo": "Undo",
    "redo": "Redo",
    "auto_fix_high": "Auto fix",
    "auto_fix_normal": "Normal fix",
    "auto_fix_off": "No fix",
    "compare": "Compare",
    "compare_arrows": "Compare",
    "compare": "Compare",
    "call_split": "Split",
    "call_merge": "Merge",
    "linear_scale": "Linear scale