#!/usr/bin/env python3
"""
add_titles_v4.py — Add meaningful title attributes to buttons that lack them.

Handles BOTH single-line and multi-line button opening tags.
Generates titles from: text content, icon name, className, onClick handler.
"""

import re
import os
import sys

# ── Icon name → human-readable mapping ──
ICON_TITLES = {
    "add": "Add", "add_circle": "Add", "add_box": "Add",
    "arrow_back": "Back", "arrow_forward": "Forward",
    "arrow_left": "Go left", "arrow_right": "Go right",
    "arrow_up": "Go up", "arrow_down": "Go down",
    "build": "Repair", "settings": "Settings", "tune": "Settings",
    "delete": "Delete", "delete_outline": "Delete",
    "edit": "Edit", "edit_square": "Edit",
    "close": "Close", "cancel": "Cancel",
    "check": "Confirm", "check_circle": "Confirm",
    "refresh": "Refresh", "sync": "Sync",
    "save": "Save", "file_download": "Download", "file_upload": "Upload",
    "more_vert": "More options", "more_horiz": "More options",
    "menu": "Menu", "search": "Search",
    "filter_list": "Filter", "sort": "Sort",
    "play_arrow": "Play", "pause": "Pause", "stop": "Stop",
    "skip_next": "Next", "skip_previous": "Previous",
    "fast_forward": "Fast forward", "fast_rewind": "Rewind",
    "volume_up": "Volume up", "volume_off": "Mute",
    "volume_down": "Volume down",
    "fullscreen": "Fullscreen", "fullscreen_exit": "Exit fullscreen",
    "minimize": "Minimize", "maximize": "Maximize",
    "open_in_new": "Open in new tab",
    "content_copy": "Copy", "content_paste": "Paste",
    "content_cut": "Cut", "undo": "Undo", "redo": "Redo",
    "zoom_in": "Zoom in", "zoom_out": "Zoom out",
    "visibility": "Show", "visibility_off": "Hide",
    "push_pin": "Pin", "attach_file": "Attach",
    "send": "Send", "share": "Share",
    "download": "Download", "upload": "Upload",
    "link": "Link", "link_off": "Unlink",
    "lock": "Lock", "lock_open": "Unlock",
    "favorite": "Favorite", "favorite_border": "Add to favorites",
    "star": "Star", "star_border": "Remove from favorites",
    "expand_more": "Expand", "expand_less": "Collapse",
    "chevron_right": "Next", "chevron_left": "Previous",
    "chevron_up": "Expand", "chevron_down": "Collapse",
    "keyboard_arrow_right": "Next", "keyboard_arrow_left": "Previous",
    "keyboard_arrow_up": "Expand", "keyboard_arrow_down": "Collapse",
    "reorder": "Reorder", "drag_indicator": "Drag",
    "open_with": "Move", "crop": "Crop",
    "tune": "Adjust settings",
    "color_lens": "Choose color", "palette": "Choose color",
    "image": "Image", "photo_library": "Photo library",
    "videocam": "Camera", "videocam_off": "Camera off",
    "mic": "Microphone", "mic_off": "Mute microphone",
    "record_voice_over": "Record", "fiber_manual_record": "Record",
    "stop_circle": "Stop recording",
    "broadcast_on_mobile": "Broadcast", "cast": "Cast",
    "tv": "Display", "monitor": "Display",
    "power_settings_new": "Power off", "logout": "Sign out",
    "login": "Sign in",
    "person": "Person", "people": "People",
    "group": "Group", "person_add": "Add person",
    "admin_panel_settings": "Admin settings",
    "account_circle": "Account", "account_balance_wallet": "Billing",
    "notifications": "Notifications", "notifications_off": "Disable notifications",
    "help": "Help", "info": "Information",
    "warning": "Warning", "error": "Error",
    "home": "Home", "dashboard": "Dashboard",
    "calendar_today": "Calendar", "event": "Event",
    "schedule": "Schedule", "timer": "Timer",
    "access_time": "Time", "history": "History",
    "bookmark": "Bookmark", "label": "Label",
    "flag": "Flag", "report": "Report",
    "print": "Print", "email": "Email",
    "chat": "Chat", "message": "Message",
    "phone": "Phone", "call": "Call",
    "location_on": "Location", "place": "Location",
    "map": "Map", "directions": "Directions",
    "local_shipping": "Shipping", "inventory": "Inventory",
    "shopping_cart": "Cart", "shopping_bag": "Bag",
    "store": "Store", "mall": "Mall",
    "account_tree": "Tree", "hub": "Hub",
    "scatter_plot": "Scatter", "grid_view": "Grid view",
    "view_list": "List view", "view_module": "Module view",
    "view_comfy": "Comfortable view", "view_compact": "Compact view",
    "format_list_bulleted": "Bulleted list",
    "format_list_numbered": "Numbered list",
    "text_fields": "Text", "format_bold": "Bold",
    "format_italic": "Italic", "format_underlined": "Underline",
    "format_align_left": "Align left",
    "format_align_center": "Align center",
    "format_align_right": "Align right",
    "title": "Title", "text_format": "Text format",
    "code": "Code", "terminal": "Terminal",
    "bug_report": "Bug report", "feedback": "Feedback",
    "science": "Experiment", "analytics": "Analytics",
    "insights": "Insights", "trending_up": "Trending up",
    "trending_down": "Trending down",
    "arrow_drop_up": "Expand", "arrow_drop_down": "Collapse",
    "radio_button_checked": "Selected", "radio_button_unchecked": "Not selected",
    "check_box": "Checked", "check_box_outline_blank": "Not checked",
    "toggle_on": "Toggle on", "toggle_off": "Toggle off",
    "swap_horiz": "Swap", "swap_vert": "Swap",
    "compare": "Compare", "scale": "Scale",
    "auto_fix_high": "Auto fix",
    "auto_awesome": "Auto enhance",
    "rocket_launch": "Launch", "bolt": "Quick action",
    "flash_on": "Enable", "flash_off": "Disable",
    "power": "Power", "tune": "Tune",
    "wifi": "WiFi", "wifi_off": "WiFi off",
    "bluetooth": "Bluetooth", "nfc": "NFC",
    "share": "Share", "file_copy": "Duplicate",
    "content_paste": "Paste", "save_alt": "Save as",
    "cloud_upload": "Upload to cloud",
    "cloud_download": "Download from cloud",
    "cloud": "Cloud", "storage": "Storage",
    "memory": "Memory", "dns": "DNS",
    "route": "Route", "alt_route": "Alternative route",
    "call_split": "Split", "call_merge": "Merge",
    "vertical_split": "Split", "horizontal_rule": "Divider",
    "drag_handle": "Drag handle",
    "arrow_drop_up": "Up", "arrow_drop_down": "Down",
    "subtitles": "Subtitles", "closed_caption": "Captions",
    "music_note": "Music", "audiotrack": "Audio",
    "library_music": "Music library",
    "queue_music": "Queue", "playlist_play": "Playlist",
    "volume_up": "Volume up", "volume_down": "Volume down",
    "hearing": "Hearing", "spatial_audio": "Spatial audio",
    "graphic_eq": "Equalizer",
    "movie": "Movie", "theaters": "Theater",
    "live_tv": "Live TV", "cell_tower": "Signal",
    "cell_tower": "Cell tower",
    "signal_cellular_alt": "Signal",
    "network_check": "Network check",
    "speed": "Speed", "speedometer": "Speedometer",
    "timer": "Timer", "alarm": "Alarm",
    "notifications_active": "Active notifications",
    "circle_notifications": "Notifications",
    "campaign": "Announce", "notification_important": "Important",
    "mark_email_read": "Mark as read",
    "mark_email_unread": "Mark as unread",
    "mark_chat_read": "Mark as read",
    "mark_chat_unread": "Mark as unread",
    "drafts": "Drafts", "inbox": "Inbox",
    "outbox": "Outbox", "send": "Send",
    "forward": "Forward", "reply": "Reply",
    "reply_all": "Reply all",
    "archive": "Archive", "unarchive": "Unarchive",
    "report_gmail_error": "Report",
    "block": "Block", "gpp_bad": "Block",
    "gpp_good": "Trust", "verified": "Verified",
    "engineering": "Engineering",
    "construction": "Construction",
    "handyman": "Repair", "plumbing": "Plumbing",
    "electrical_services": "Electrical",
    "roofing": "Roofing", "foundation": "Foundation",
    "paint": "Paint", "brush": "Brush",
    "format_paint": "Paint roller",
    "wallpaper": "Wallpaper", "texture": "Texture",
    "extension": "Extension", "plugin": "Plugin",
    "widgets": "Widgets", "dashboard_customize": "Customize dashboard",
    "category": "Category", "collections": "Collections",
    "gallery_thumbnail": "Thumbnail",
    "view_carousel": "Carousel",
    "slideshow": "Slideshow",
    "motion_photos_on": "Live photo",
    "burst_mode": "Burst",
    "grid_on": "Grid overlay",
    "flash_auto": "Auto flash",
    "hdr_on": "HDR",
    "wb_sunny": "White balance",
    " wb_cloudy": "Cloudy",
    "nightlight": "Night mode",
    "dark_mode": "Dark mode", "light_mode": "Light mode",
    "palette": "Palette",
    "invert_colors": "Invert colors",
    "colorize": "Colorize",
    "gradient": "Gradient",
    "blur_on": "Blur on", "blur_off": "Blur off",
    "grain": "Grain", "contrast": "Contrast",
    "brightness_1": "Brightness",
    "brightness_5": "Increase brightness",
    "brightness_4": "Decrease brightness",
    "exposure": "Exposure",
    "filter_vintage": "Vintage filter",
    "filter_drama": "Drama filter",
    "filter_b_and_w": "B&W filter",
    "filter_none": "No filter",
    "filter_center_focus": "Focus",
    "dehaze": "Dehaze",
    "vignette": "Vignette",
    "blur_circular": "Tilt shift",
    "transform": "Transform",
    "flip": "Flip", "rotate_right": "Rotate right",
    "rotate_left": "Rotate left",
    "crop_square": "Crop", "crop_free": "Free crop",
    "crop_landscape": "Landscape crop",
    "crop_portrait": "Portrait crop",
    "straighten": "Straighten",
    "tune": "Tune",
    "healing": "Heal", "auto_fix_normal": "Auto fix",
    "auto_fix_high": "Enhance",
    "leak_remove": "Remove leak",
    "wb_twilight": "White balance",
    "camera": "Camera", "photo_camera": "Take photo",
    "switch_camera": "Switch camera",
    "flip_camera_ios": "Flip camera",
    "burst_mode": "Burst mode",
    "timer": "Timer",
    "flash_on": "Flash on", "flash_off": "Flash off",
    "hdr_on": "HDR on", "hdr_off": "HDR off",
    "grid_on": "Grid on", "grid_off": "Grid off",
    "settings_brightness": "Brightness settings",
    " exposure": "Exposure",
    # Specific app icons
    "subtitles": "Subtitles", "closed_caption": "Captions",
    "menu_book": "Bible", "book": "Book",
    "library_books": "Library",
    "bookmark_added": "Bookmark added",
    "auto_stories": "Auto stories",
    "local_library": "Library",
    "speaker": "Speaker", "groups": "Groups",
    "campaign": "Campaign",
    "church": "Church", "mosque": "Mosque",
    "temple_buddhist": "Temple",
    "gpp_maybe": "Verify",
    "fact_check": "Fact check",
    "policy": "Policy",
    "verified_user": "Verified",
    "security": "Security", "shield": "Shield",
    "vpn_lock": "VPN",
    "enhanced_encryption": "Encryption",
    "no_encryption": "No encryption",
    "lock_reset": "Reset lock",
    "password": "Password",
    "fingerprint": "Fingerprint",
    "face": "Face ID",
    "qr_code": "QR code",
    "qr_code_scanner": "Scan QR code",
    "document_scanner": "Scanner",
    "currency_exchange": "Currency",
    "monetization_on": "Monetize",
    "paid": "Paid", "redeem": "Redeem",
    "card_giftcard": "Gift card",
    "account_balance": "Account balance",
    "request_quote": "Request quote",
    "receipt": "Receipt",
    "local_atm": "ATM",
    "savings": "Savings",
    "point_of_sale": "Point of sale",
    "inventory_2": "Inventory",
    "add_shopping_cart": "Add to cart",
    "remove_shopping_cart": "Remove from cart",
    "remove": "Remove", "add_circle_outline": "Add",
    "remove_circle": "Remove", "remove_circle_outline": "Remove",
    "indeterminate_check_box": "Indeterminate",
    "select_all": "Select all", "deselect": "Deselect all",
    "flip_to_back": "Send to back",
    "flip_to_front": "Bring to front",
    "vertical_align_top": "Align top",
    "vertical_align_bottom": "Align bottom",
    "vertical_align_center": "Align middle",
    "horizontal_align_left": "Align left",
    "horizontal_align_right": "Align right",
    "space_bar": "Space",
    "keyboard": "Keyboard",
    "input": "Input",
    "keyboard_hide": "Hide keyboard",
    "keyboard_show": "Show keyboard",
    "arrow_back_ios": "Go back",
    "arrow_forward_ios": "Go forward",
    "first_page": "First page", "last_page": "Last page",
    "chevron_right": "Next page", "chevron_left": "Previous page",
    "more_horiz": "More options",
    "unfold_more": "Expand all", "unfold_less": "Collapse all",
    "select_all": "Select all",
    "drag_indicator": "Drag to reorder",
    "swap_vert": "Swap vertical",
    "swap_horiz": "Swap horizontal",
    "drive_file_rename_outline": "Rename",
    "content_cut": "Cut",
    "content_copy": "Copy",
    "content_paste": "Paste",
    "file_copy": "Copy file",
    "file_duplicate": "Duplicate",
    "drive_file_move": "Move",
    "create_new_folder": "New folder",
    "folder": "Folder", "folder_open": "Open folder",
    "folder_special": "Special folder",
    "upload_file": "Upload file",
    "download_done": "Download complete",
    "cloud_upload": "Upload to cloud",
    "cloud_download": "Download from cloud",
    "attach_money": "Attach price",
    "monetization_on": "Monetize",
    "analytics": "Analytics",
    "insights": "Insights",
    "assessment": "Assessment",
    "bar_chart": "Bar chart",
    "show_chart": "Line chart",
    "pie_chart": "Pie chart",
    "stacked_bar_chart": "Stacked bar chart",
    "scatter_plot": "Scatter plot",
    "bubble_chart": "Bubble chart",
    "candlestick_chart": "Candlestick chart",
    "multiline_chart": "Area chart",
    "area_chart": "Area chart",
    "radar": "Radar chart",
    "waterfall_chart": "Waterfall chart",
    "funnel_chart": "Funnel chart",
    "trekkers": "Treemap",
    "leaderboard": "Leaderboard",
    "equalizer": "Equalizer",
    "timeline": "Timeline",
    "history_toggle_off": "Clock history",
    "timer_10": "10-second timer",
    "timer_3": "3-second timer",
    "hourglass_bottom": "Loading",
    "hourglass_top": "Loading",
    "sync_problem": "Sync issue",
    "update": "Update",
    "system_update": "System update",
    "autorenew": "Refresh", "cached": "Cached",
    "loop": "Loop", "repeat": "Repeat",
    "repeat_one": "Repeat once",
    "shuffle": "Shuffle",
    "queue": "Queue", "playlist_add": "Add to playlist",
    "playlist_remove": "Remove from playlist",
    "library_add": "Add to library",
    "library_add_check": "Add to library",
    "remove_from_queue": "Remove from queue",
    "clear_all": "Clear all",
    "delete_sweep": "Delete all",
    "select_all": "Select all",
    "crop": "Crop",
    "rotate_right": "Rotate right",
    "rotate_left": "Rotate left",
    "flip": "Flip",
    "straighten": "Straighten",
    "aspect_ratio": "Aspect ratio",
    "fit_screen": "Fit screen",
    "crop_16_9": "Crop to 16:9",
    "crop_4_3": "Crop to 4:3",
    "crop_square": "Crop to square",
    "crop_landscape": "Crop to landscape",
    "crop_portrait": "Crop to portrait",
    "movie_filter": "Movie filter",
    "photo_filter": "Photo filter",
    "texture": "Texture",
    "gradient": "Gradient",
    "blur_on": "Blur",
    "grain": "Grain effect",
    "contrast": "Contrast",
    "dehaze": "Dehaze",
    "vignette": "Vignette",
    "healing": "Heal spots",
    "healing": "Heal",
    "leak_remove": "Remove light leak",
    "magic_eraser": "Magic eraser",
    "auto_fix_normal": "Auto fix",
    "auto_fix_high": "Enhance",
    "filter_hdr": "HDR filter",
    "filter_vintage": "Vintage filter",
    "filter_drama": "Drama filter",
    "filter_b_and_w": "Black & white",
    "filter_none": "No filter",
    "filter_tilt_shift": "Tilt shift",
    "filter_frames": "Frame filter",
    "filter_list": "Filter list",
    "filter_alt": "Filter",
    "sort": "Sort", "sort_by_alpha": "Sort by name",
    "sort_by_size": "Sort by size",
    "sort_by_date": "Sort by date",
    "arrow_upward": "Sort ascending",
    "arrow_downward": "Sort descending",
    "view_headline": "Headline view",
    "view_agenda": "Agenda view",
    "view_day": "Day view",
    "view_week": "Week view",
    "view_month": "Month view",
    "view_year": "Year view",
    "date_range": "Date range",
    "event_available": "Available",
    "event_busy": "Busy",
    "event_seat": "Reserved",
    "notification_important": "Important",
    "markunread_mailbox": "Mark unread",
    "mark_email_read": "Mark as read",
    "mark_email_unread": "Mark as unread",
    "drafts": "Drafts",
    "send": "Send",
    "forward": "Forward",
    "reply": "Reply",
    "reply_all": "Reply all",
    "archive": "Archive",
    "unarchive": "Unarchive",
    "delete": "Delete",
    "report": "Report",
    "block": "Block",
    "gpp_bad": "Block",
    "gpp_good": "Trust",
    "flag": "Flag",
    "label": "Label",
    "label_off": "Remove label",
    "label_important": "Important",
    "mark_as_unread": "Mark unread",
    "mark_as_read": "Mark read",
    "move_to_inbox": "Move to inbox",
    "delete_forever": "Delete permanently",
    "restore": "Restore",
    "restore_from_trash": "Restore from trash",
    "undo": "Undo",
    "redo": "Redo",
    "zoom_in": "Zoom in",
    "zoom_out": "Zoom out",
    "center_focus_strong": "Center focus",
    "center_focus_weak": "Soft focus",
    "fullscreen": "Fullscreen",
    "fullscreen_exit": "Exit fullscreen",
    "aspect_ratio": "Aspect ratio",
    "settings_overscan": "Overscan",
    "open_in_full": "Open full",
    "close_fullscreen": "Close fullscreen",
    "minimize": "Minimize",
    "maximize": "Maximize",
    "call_made": "Outgoing",
    "call_received": "Incoming",
    "call_merge": "Merge calls",
    "call_split": "Split call",
    "ring_volume": "Ring volume",
    "phone_in_talk": "In call",
    "phone_paused": "Paused",
    "dialpad": "Keypad",
    "contacts": "Contacts",
    "contact_phone": "Contact phone",
    "contact_mail": "Contact email",
    "voicemail": "Voicemail",
    "sip": "SIP",
    "video_call": "Video call",
    "screen_share": "Screen share",
    "stop_screen_share": "Stop sharing",
    "present_to_all": "Present to all",
    "picture_in_picture": "Picture-in-picture",
    "pip_exit": "Exit PiP",
    "closed_caption": "Captions",
    "record_voice_over": "Record voice over",
    "speed": "Speed",
    "audiotrack": "Audio track",
    "graphic_eq": "Equalizer",
    "spatial_audio": "Spatial audio",
    "surround_sound": "Surround sound",
    "sound_detection_dog_barking": "Sound detection",
    "hearing": "Hearing",
    "hearing_disabled": "Hearing disabled",
    "mic_external_on": "External mic",
    "mic_external_off": "External mic off",
    "noise_aware": "Noise detection",
    "noise_control_off": "Noise control off",
    "spatial_tracking": "Spatial tracking",
    "motion_sensor_active": "Motion sensor",
    # App-specific
    "arrow_back": "Back", "home": "Home",
    "dashboard": "Dashboard",
    "play_circle": "Play",
    "pause_circle": "Pause",
    "stop_circle": "Stop",
    "skip_next": "Skip next",
    "skip_previous": "Skip previous",
    "fast_forward": "Fast forward",
    "fast_rewind": "Rewind",
    "replay": "Replay",
    "forward_30": "Forward 30s",
    "replay_10": "Replay 10s",
    "replay_30": "Replay 30s",
    "slow_motion_video": "Slow motion",
    "speed": "Playback speed",
    "flip_to_front": "Bring to front",
    "flip_to_back": "Send to back",
    "picture_in_picture_alt": "Picture-in-picture",
    "theaters": "Theater mode",
    "live_tv": "Live TV",
    "ondemand_video": "On demand",
    "video_library": "Video library",
    "subscriptions": "Subscriptions",
    "whatshot": "Trending",
    "local_fire_department": "Hot",
    "emoji_events": "Top",
    "workspace_premium": "Premium",
    "military_tech": "Military",
    "emoji_events": "Awards",
    # Church/worship specific
    "church": "Church",
    "groups": "Groups",
    "group_add": "Add group",
    "person_add": "Add person",
    "person_remove": "Remove person",
    "people_alt": "People",
    "engineering": "Team",
    "diversity_3": "Diversity",
    "waving_hand": "Greeting",
    "handshake": "Partnership",
    "volunteer_activism": "Volunteer",
    "redeem": "Redeem",
    "workspace_premium": "Premium",
    "military_tech": "Award",
    "emoji_events": "Achievement",
    "celebration": "Celebration",
    "campaign": "Announcement",
    "notifications_active": "Active",
    "notifications": "Notifications",
    "circle_notifications": "Circle notifications",
    "notifications_none": "No notifications",
    "notifications_off": "Notifications off",
    "notifications_paused": "Paused",
    "mark_email_read": "Mark read",
    "mark_email_unread": "Mark unread",
    "mark_chat_read": "Mark read",
    "mark_chat_unread": "Mark unread",
    "markunread_mailbox": "Unread mailbox",
    "mark_as_unread": "Unread",
    "mark_as_read": "Read",
    "inbox": "Inbox",
    "outbox": "Outbox",
    "send": "Send",
    "drafts": "Drafts",
    "delete_sweep": "Sweep",
    "select_all": "Select all",
    "deselect": "Deselect",
    "radio_button_checked": "Selected",
    "radio_button_unchecked": "Unselected",
    "check_box": "Checked",
    "check_box_outline_blank": "Unchecked",
    "toggle_on": "On", "toggle_off": "Off",
    "swap_horiz": "Swap",
    "swap_vert": "Swap vertical",
    "compare": "Compare",
    "call_split": "Split",
    "call_merge": "Merge",
    "vertical_split": "Vertical split",
    "horizontal_split": "Horizontal split",
    "view_column": "Column view",
    "view_sidebar": "Sidebar",
    "view_quilt": "Quilt view",
    "view_timeline": "Timeline view",
    "view_dashboard": "Dashboard view",
    "space_dashboard": "Space dashboard",
    "dashboard_customize": "Customize",
    "auto_graph": "Auto chart",
    "leaderboard": "Leaderboard",
    "score": "Score",
    "golf": "Golf",
    "sports_esports": "Gaming",
    "emoji_events": "Events",
    "military_tech": "Trophy",
    "school": "School",
    "history_edu": "History",
    "science": "Science",
    "biotech": "Biotech",
    "psychology": "Psychology",
    "architecture": "Architecture",
    "engineering": "Engineering",
    "construction": "Construction",
    "precision_manufacturing": "Manufacturing",
    "agriculture": "Agriculture",
    "grass": "Grass",
    "park": "Park",
    "forest": "Forest",
    "landscape": "Landscape",
    "terrain": "Terrain",
    "beach_access": "Beach",
    "pool": "Pool",
    "hot_tub": "Hot tub",
    "spa": "Spa",
    "fitness_center": "Fitness",
    "sports_gymnastics": "Gymnastics",
    "sports_soccer": "Soccer",
    "sports_basketball": "Basketball",
    "sports_football": "Football",
    "sports_baseball": "Baseball",
    "sports_tennis": "Tennis",
    "sports_golf": "Golf",
    "sports_motorsports": "Motorsport",
    "sports_rugby": "Rugby",
    "sports_cricket": "Cricket",
    "sports_volleyball": "Volleyball",
    "sports_hockey": "Hockey",
    "sports_mma": "MMA",
    "sports_martial_arts": "Martial arts",
    "sports_kabaddi": "Kabaddi",
    "sports_handball": "Handball",
    "sports_baseball": "Baseball",
    "sports_basketball": "Basketball",
    "sports_esports": "Esports",
    "emoji_events": "Awards",
    "military_tech": "Medal",
    "workspace_premium": "Premium",
    "celebration": "Celebration",
    "party_mode": "Party",
    "celebration": "Celebrate",
    "cake": "Birthday",
    "card_giftcard": "Gift",
    "redeem": "Redeem",
    "confirmation_number": "Ticket",
    "event": "Event",
    "event_available": "Available",
    "event_busy": "Busy",
    "event_seat": "Seat",
    "calendar_today": "Today",
    "calendar_month": "Month",
    "date_range": "Date range",
    "date_picker": "Pick date",
    "time_picker": "Pick time",
    "timer": "Timer",
    "alarm": "Alarm",
    "alarm_add": "Add alarm",
    "alarm_off": "Alarm off",
    "alarm_on": "Alarm on",
    "snooze": "Snooze",
    "update": "Update",
    "system_update": "Update system",
    "system_update_alt": "Update",
    "download": "Download",
    "upload": "Upload",
    "file_download": "Download file",
    "file_upload": "Upload file",
    "cloud_download": "Download from cloud",
    "cloud_upload": "Upload to cloud",
    "save": "Save", "save_alt": "Save as",
    "save_as": "Save as",
    "backup": "Backup",
    "restore": "Restore",
    "import_export": "Import/export",
    "file_copy": "Copy file",
    "drive_file_move": "Move file",
    "create_new_folder": "New folder",
    "folder": "Folder",
    "folder_open": "Open folder",
    "folder_special": "Special folder",
    "folder_off": "Folder off",
    "attach_file": "Attach file",
    "attach_money": "Attach price",
    "link": "Link",
    "link_off": "Unlink",
    "content_copy": "Copy",
    "content_paste": "Paste",
    "content_cut": "Cut",
    "content_duplicate": "Duplicate",
    "content_duo": "Duo",
    "content_filter": "Filter",
    "content_off": "Content off",
    "content_paste_go": "Paste and go",
    "content_paste_off": "Paste disabled",
    "content_paste_search": "Paste search",
    "content_paste_top": "Paste to top",
    "dashboard_customize": "Customize",
    # Default fallback icons
    "settings": "Settings",
    "info": "Info",
    "help": "Help",
    "warning": "Warning",
    "error": "Error",
}

# ── onClick handler name → human-readable ──
def handler_to_title(name):
    """Convert camelCase handler name to readable title."""
    name = name.lstrip('_')
    # Remove common prefixes
    for prefix in ['handle', 'on', 'do']:
        if name.startswith(prefix) and len(name) > len(prefix):
            rest = name[len(prefix):]
            if rest[0].isupper():
                name = rest
                break
    # Split camelCase
    words = re.sub(r'([a-z])([A-Z])', r'\1 \2', name).split()
    return ' '.join(w.capitalize() for w in words) if words else name


def extract_button_context(tag_text):
    """Extract context from a button opening tag to generate a title."""
    icon_name = None
    text_hint = None
    class_hint = None
    
    # Extract Icon name
    icon_match = re.search(r'<Icon\s+name="([^"]+)"', tag_text)
    if icon_match:
        icon_name = icon_match.group(1)
    
    # Also check for <Icon name=... without quotes
    if not icon_name:
        icon_match2 = re.search(r'