/**
 * Built-in theme presets. Every preset is a plain ThemeLayout, so users can
 * open it in the Theme Editor and change anything. Fonts are ones the overlays
 * already ship locally (public/fonts/google/google-fonts.css), so presets work
 * offline in OBS.
 *
 * Phase 1 ships two presets used to prove the renderer in OBS; the remaining
 * five from the plan land in Phase 3.
 */
import type { LayerAnimation, ThemeLayout } from "./types";

const none: LayerAnimation = { preset: "none", duration: 0, delay: 0, easing: "out-cubic" };
const anim = (preset: LayerAnimation["preset"], duration: number, delay = 0, extra: Partial<LayerAnimation> = {}): LayerAnimation => ({
  preset,
  duration,
  delay,
  easing: "out-expo",
  ...extra,
});

/** 1 · Aurora Glass — dark rounded bar with a slow colour drift (Genesis 1:1 reference). */
export const AURORA_GLASS: ThemeLayout = {
  version: 1,
  format: "lower-third",
  swap: "content",
  layers: [
    {
      id: "bar",
      name: "Bar",
      type: "box",
      anchor: "bottom-center",
      x: 960,
      y: 1024,
      w: 1560,
      h: 214,
      style: {
        radius: 18,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.12)",
        shadow: "0 24px 60px rgba(0,0,0,0.45)",
        gradient: {
          type: "linear",
          angle: 100,
          stops: [
            { color: "#070b18", at: 0 },
            { color: "#0c1430", at: 22 },
            { color: "#1f3c9a", at: 42 },
            { color: "#9a2f78", at: 58 },
            { color: "#d4513a", at: 72 },
            { color: "#1a1030", at: 88 },
            { color: "#070b18", at: 100 },
          ],
        },
      },
      loop: { preset: "drift", duration: 14000 },
      in: anim("wipe-left", 750),
      out: anim("wipe-left", 450, 180, { easing: "in-out" }),
    },
    {
      id: "reference",
      name: "Reference",
      type: "text",
      parentId: "bar",
      content: "{book} {chapterVerse} ({translation})",
      anchor: "top-left",
      x: 40,
      y: 26,
      w: 1100,
      h: "auto",
      style: {
        fontFamily: "Montserrat",
        fontSize: 20,
        fontWeight: 600,
        letterSpacing: 2.4,
        textTransform: "uppercase",
        color: "rgba(255,255,255,0.88)",
      },
      in: anim("fade", 400, 300),
      out: anim("fade", 220),
    },
    {
      id: "verse",
      name: "Verse",
      type: "text",
      parentId: "bar",
      content: "{text}",
      anchor: "center",
      x: 780,
      y: 122,
      w: 1420,
      h: 132,
      style: {
        fontFamily: "Inter",
        fontSize: 34,
        minFontSize: 22,
        fontWeight: 500,
        lineHeight: 1.35,
        align: "center",
        color: "#ffffff",
        verseNumberColor: "rgba(255,255,255,0.7)",
      },
      in: anim("word-rise", 520, 380, { stagger: 22 }),
      out: anim("fade", 240),
    },
  ],
};

/**
 * 3 · Chapter Number — full-width dark band: red translation, big chapter:verse
 * and book stacked right-aligned, thin red divider, verse to the right
 * (Matthew 28:19-20 reference).
 */
export const CHAPTER_NUMBER: ThemeLayout = {
  version: 1,
  format: "lower-third",
  swap: "content",
  layers: [
    {
      id: "band",
      name: "Band",
      type: "box",
      anchor: "bottom-left",
      x: 0,
      y: 1080,
      w: 1920,
      h: 250,
      style: {
        fill: "rgba(36,33,32,0.88)",
        borderWidth: 0,
      },
      in: anim("slide-up", 600, 0, { distance: 60 }),
      out: anim("slide-up", 420, 200, { distance: 60, easing: "in-out" }),
    },
    {
      id: "top-rule",
      name: "Top rule",
      type: "divider",
      parentId: "band",
      anchor: "top-left",
      x: 0,
      y: 0,
      w: 1920,
      h: 3,
      style: { fill: "rgba(160,64,50,0.9)" },
      in: anim("grow-x", 600, 100),
      out: none,
    },
    {
      id: "translation",
      name: "Translation",
      type: "text",
      parentId: "band",
      content: "{translation}",
      anchor: "top-right",
      x: 441,
      y: 40,
      w: 300,
      h: "auto",
      style: { fontFamily: "Arial", fontSize: 24, fontWeight: 400, letterSpacing: 1, textTransform: "uppercase", align: "right", color: "#e0453a" },
      in: anim("fade", 350, 350),
      out: anim("fade", 200),
    },
    {
      id: "chapter-verse",
      name: "Chapter:Verse",
      type: "text",
      parentId: "band",
      content: "{chapterVerse}",
      anchor: "top-right",
      x: 441,
      y: 76,
      w: 420,
      h: 74,
      style: { fontFamily: "Arial", fontSize: 58, minFontSize: 36, fontWeight: 700, lineHeight: 1, letterSpacing: 1, align: "right", color: "#ffffff" },
      in: anim("pop", 520, 250),
      out: anim("fade", 200),
    },
    {
      id: "book",
      name: "Book",
      type: "text",
      parentId: "band",
      content: "{book}",
      anchor: "top-right",
      x: 441,
      y: 152,
      w: 420,
      h: "auto",
      style: { fontFamily: "Oswald", fontSize: 40, minFontSize: 26, fontWeight: 500, lineHeight: 1.1, letterSpacing: 2, textTransform: "uppercase", align: "right", color: "#ffffff", maxLines: 1 },
      in: anim("fade", 400, 400),
      out: anim("fade", 200),
    },
    {
      id: "divider",
      name: "Divider",
      type: "divider",
      parentId: "band",
      anchor: "top-left",
      x: 498,
      y: 32,
      w: 2,
      h: 186,
      style: { fill: "rgba(160,64,50,0.85)" },
      in: anim("grow-y", 500, 300),
      out: none,
    },
    {
      id: "verse",
      name: "Verse",
      type: "text",
      parentId: "band",
      content: "{text}",
      anchor: "middle-left",
      x: 558,
      y: 125,
      w: 1200,
      h: 200,
      style: { fontFamily: "Arial", fontSize: 33, minFontSize: 22, fontWeight: 400, lineHeight: 1.4, letterSpacing: 1.3, align: "left", color: "#f4f4f4", verseNumberColor: "#e0453a" },
      in: anim("line-rise", 520, 420, { stagger: 60 }),
      out: anim("fade", 220),
    },
  ],
};

/**
 * 4 · Caption Rule — no panel: bold reference, a thin white rule, verse below,
 * all shadowed for readability over any shot (2 Peter 1:20 reference).
 */
export const CAPTION_RULE: ThemeLayout = {
  version: 1,
  format: "lower-third",
  swap: "content",
  layers: [
    {
      id: "reference",
      name: "Reference",
      type: "text",
      content: "{reference}",
      anchor: "top-left",
      x: 76,
      y: 792,
      w: 1400,
      h: "auto",
      style: {
        fontFamily: "Arial",
        fontSize: 64,
        minFontSize: 36,
        fontWeight: 700,
        lineHeight: 1.1,
        letterSpacing: -0.5,
        color: "#ffffff",
        textShadow: "0 2px 8px rgba(0,0,0,0.6)",
        maxLines: 1,
      },
      in: anim("slide-up", 480, 0, { distance: 18 }),
      out: anim("fade", 220, 120),
    },
    {
      id: "rule",
      name: "Rule",
      type: "divider",
      anchor: "top-left",
      x: 78,
      y: 870,
      w: 848,
      h: 3,
      style: { fill: "rgba(255,255,255,0.95)", shadow: "0 1px 6px rgba(0,0,0,0.45)" },
      in: anim("grow-x", 520, 140),
      out: anim("fade", 200, 60),
    },
    {
      id: "verse",
      name: "Verse",
      type: "text",
      content: "{text}",
      anchor: "top-left",
      x: 76,
      y: 886,
      w: 1790,
      h: 186,
      style: {
        fontFamily: "Arial",
        fontSize: 56,
        minFontSize: 30,
        fontWeight: 400,
        lineHeight: 1.26,
        letterSpacing: -1.6,
        align: "left",
        verticalAlign: "top",
        color: "#ffffff",
        textShadow: "0 2px 8px rgba(0,0,0,0.65)",
        verseNumberColor: "rgba(255,255,255,0.75)",
      },
      in: anim("line-rise", 520, 300, { stagger: 60 }),
      out: anim("fade", 220),
    },
  ],
};

/**
 * 5 · Accent Card — white card with an orange left bar, bold uppercase
 * reference and dark verse text (Ephesians 4:15 reference).
 */
export const ACCENT_CARD: ThemeLayout = {
  version: 1,
  format: "lower-third",
  swap: "content",
  layers: [
    {
      id: "card",
      name: "Card",
      type: "box",
      anchor: "top-left",
      x: 83,
      y: 800,
      w: 1752,
      h: 204,
      style: { fill: "#ffffff", shadow: "0 10px 30px rgba(0,0,0,0.28)" },
      in: anim("wipe-left", 620),
      out: anim("wipe-right", 420, 160, { easing: "in-out" }),
    },
    {
      id: "accent",
      name: "Accent bar",
      type: "box",
      parentId: "card",
      anchor: "top-left",
      x: 0,
      y: 0,
      w: 20,
      h: 204,
      style: { fill: "#f6a11a" },
      in: anim("grow-y", 420, 120),
      out: none,
    },
    {
      id: "reference",
      name: "Reference",
      type: "text",
      parentId: "card",
      content: "{reference}",
      anchor: "top-left",
      x: 48,
      y: 20,
      w: 1660,
      h: "auto",
      style: { fontFamily: "Montserrat", fontSize: 32, minFontSize: 20, fontWeight: 800, lineHeight: 1.2, letterSpacing: 0.5, textTransform: "uppercase", color: "#111111", maxLines: 1 },
      in: anim("fade", 360, 320),
      out: anim("fade", 200),
    },
    {
      id: "verse",
      name: "Verse",
      type: "text",
      parentId: "card",
      content: "{text}",
      anchor: "top-left",
      x: 48,
      y: 66,
      w: 1640,
      h: 126,
      style: { fontFamily: "Montserrat", fontSize: 42, minFontSize: 24, fontWeight: 500, lineHeight: 1.12, align: "left", verticalAlign: "top", color: "#1a1a1a", verseNumberColor: "#f6a11a" },
      in: anim("line-rise", 500, 380, { stagger: 60 }),
      out: anim("fade", 220),
    },
  ],
};

export const THEME_PRESETS: Array<{ id: string; name: string; layout: ThemeLayout }> = [
  { id: "preset-aurora-glass", name: "Aurora Glass", layout: AURORA_GLASS },
  { id: "preset-chapter-number", name: "Chapter Number", layout: CHAPTER_NUMBER },
  { id: "preset-caption-rule", name: "Caption Rule", layout: CAPTION_RULE },
  { id: "preset-accent-card", name: "Accent Card", layout: ACCENT_CARD },
];
